-- Based on lasvegas.db

-- Ideas for queries to run:

-- amenities, leisure <especially "gambling" or "gaming" or "casino">
-- tourism?
-- spread of users?
-- Count the FIXME's
-- street name "Kmart" or "McDonalds's", did that happen?
-- Mohave, AZ, ie out-of-state
-- GNIS that have a name, but no addr data
-- Compare redundant, overlapping DATABASE
--     bicycles
--     amenities, etc
--     water & waterway

-- ############################################

-- lat or lon out of range
-- FIND THE "corners" OF THE MAP AREA

SELECT MAX(lat), MIN(lon) FROM nodes;
-- 36.6149917|-115.5809186 (node doesn't exist!)
SELECT MAX(lat), MAX(lon) FROM nodes;
-- 36.6149917|-114.2110022
SELECT MIN(lat), MAX(lon) FROM nodes;
-- 35.7570021|-114.2110022
SELECT MIN(lat), MIN(lon) FROM nodes;
-- 35.7570021|-115.5809186

-- NE to SW:
sqlite> SELECT id, lat, lon FROM nodes
   ...> ORDER BY lat ASC, lon DESC LIMIT 5;
602032956|35.7570021|-114.6924896 -- Southernmost node
778692966|35.757016|-114.9130231
137067628|35.757038|-115.120138
603484371|35.7570513|-114.4847471
137169544|35.7570547|-115.0951852
-- SE to NW:
sqlite> SELECT id, lat, lon  FROM nodes
   ...> ORDER BY lon DESC LIMIT 5;
603591076|36.4397958|-114.2110022 -- easternmost node
610205821|36.0140901|-114.2110121
2054187418|36.273785|-114.2110645
2059827349|36.4874978|-114.2110835
599430763|36.0191712|-114.2110935

-- ############################################

-- COUNT OF "highway"="proposed"
SELECT COUNT(highway) FROM way_tags
WHERE highway = 'proposed';
256

-- ############################################

-- Example of data that almost looks boolean but's not
sqlite> select hgv, count(*) as count from way_tags group by hgv order by count desc;
hgv         count
----------  ----------
            72334
designated  455
yes         28


-- ############################################

-- OVERLAPPING DATA

-- example of overlapping data (filtering by elevation ("ele")):
SELECT DISTINCT name, ele, landuse, leisure, natural, place, gnis_feature_type, amenity, waterway, aeroway
FROM _tags
WHERE ele > 0;


-- "water" types example
sqlite> SELECT natural, water, waterway, gnis_ftype, COUNT(*) AS count FROM way
tags WHERE natural != "" GROUP BY natural ORDER BY count DESC;
natural       water       waterway    gnis_ftype  count
------------  ----------  ----------  ----------  ----------
sand                                              626
water         pond                                265
desert                                            168
heath                                             74
scrub                                             44
cliff                                             21
wood                                              7
mud                                               4
beach                                             3
scree                                             3
wetland                               Wash        2
water_park                river                   1
wetlands                              Wash        1


SELECT water, waterway, COUNT(*) AS count FROM way_tags 
WHERE water != "" OR waterway != "" GROUP BY waterway ORDER BY count DESC;
water         waterway    count
------------  ----------  ----------
              drain       186
              stream      51
pond                      44
              river       29
              weir        20
              dam         7
              wadi        6
              riverbank   114
              
              
-- ############################################

-- ele containing units of measurement
SELECT * FROM node_tags
WHERE ele GLOB '[0-9]*[a-z]';
1491001731|node||||||||navigationaid||||||2141 ft||||||||||||||||||||Las Vegas
VORTAC||||||LAS||||FAA;bing_imagery_0.06m_200706|||
1491003394|node||||||||navigationaid||||||3650 ft||||||||||||||||||||Boulder City VORTAC||||||BLD||||FAA|||

-- ############################################

-- Full address in one field
-- First caught wind of this in file "lvhwy_audit.txt", generated by
-- "audit_highway.py", neither of which was much use otherwise.

SELECT tourism, name, COUNT(*) AS count FROM node_tags
WHERE name GLOB '*Circus*';
hotel|Circus Circus 2880 Las Vegas Boulevard NV 89109 Las Vegas Vereinigte Staaten von Amerika|1

sqlite> select type, tourism, name from node_tags
   ...> where name GLOB '*NV [0-9]*';
type    tourism     name
------  ----------  -----------------------------------
node    hotel       Circus Circus 2880 Las Vegas Boulevard NV 89109 La

-- this outputs both:
SELECT tourism, name
FROM
(SELECT tourism, name FROM node_tags
UNION
SELECT tourism, name FROM way_tags)
GROUP BY name 
HAVING name GLOB '*[0-9][0-9][0-9][0-9][0-9]*';
/*hotel|Circus Circus 2880 Las Vegas Boulevard NV 89109 Las Vegas Vereinigte Staat
en von Amerika
hotel|Element Las Vegas Summerline 10555 Discovery Drive*/

-- ############################################